-- Tabela para Armazenar Configurações Globais (Senhas do VIP, Checkout, etc.)
CREATE TABLE IF NOT EXISTS apex_config (
    key TEXT PRIMARY KEY,
    value JSONB NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Inserir as Configurações Iniciais do Ciclo 2026
INSERT INTO apex_config (key, value)
VALUES ('main_config', '{
    "checkout_url": "https://lastlink.com/p/CAA303628/checkout-payment/",
    "access_key": "apex_vip_access_2026_secure",
    "official_domain": ""
}')
ON CONFLICT (key) DO NOTHING;

-- Tabela para Logs de Tentativas de Clonagem e Acessos Suspeitos
CREATE TABLE IF NOT EXISTS apex_clones_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    domain TEXT NOT NULL,
    path TEXT NOT NULL,
    timestamp TIMESTAMPTZ NOT NULL,
    original_link TEXT, -- Novo: Captura o link que o clonador colocou
    hijack_active BOOLEAN DEFAULT FALSE, -- Novo: Define se o sequestro está ativo para este domínio
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Script para atualizar tabela existente se necessário:
-- ALTER TABLE apex_clones_log ADD COLUMN IF NOT EXISTS original_link TEXT;
-- ALTER TABLE apex_clones_log ADD COLUMN IF NOT EXISTS hijack_active BOOLEAN DEFAULT FALSE;

-- Habilitar RLS (Opcional, mas recomendado)
ALTER TABLE apex_config ENABLE ROW LEVEL SECURITY;
ALTER TABLE apex_clones_log ENABLE ROW LEVEL SECURITY;

-- Criar políticas básicas se necessário (por enquanto usando Service Role)
